DROP TABLE IF EXISTS message_votes;
DROP TABLE IF EXISTS attachments;

ALTER TABLE messages DROP COLUMN IF EXISTS dislikes;
ALTER TABLE messages DROP COLUMN IF EXISTS likes;
ALTER TABLE messages DROP COLUMN IF EXISTS edited_at;
ALTER TABLE chats    DROP COLUMN IF EXISTS creator_id;
ALTER TABLE chats    DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE users    DROP COLUMN IF EXISTS rating;
ALTER TABLE users    DROP COLUMN IF EXISTS avatar_url;
