{{- $_ := set . "merged" (include "app.mergedValues" . | fromYaml) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .merged.IMAGE_NAME }}
  name: {{ .merged.IMAGE_NAME }}
{{- /*
       DO NOT PLACE ACTUAL VALUES IN REPO
*/}}
stringData:
  SECRET_ENV: "placeholder"
