CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS chat;
CREATE SCHEMA IF NOT EXISTS media;

GRANT ALL ON SCHEMA auth TO CURRENT_USER;
GRANT ALL ON SCHEMA users TO CURRENT_USER;
GRANT ALL ON SCHEMA chat TO CURRENT_USER;
GRANT ALL ON SCHEMA media TO CURRENT_USER;
