<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>

    <groupId>ru.lambdahub</groupId>
    <artifactId>chat-service</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>chat-service</name>

    <modules>
        <module>chat-service-api</module>
        <module>chat-service-db</module>
        <module>chat-service-impl</module>
    </modules>

    <properties>
        <java.version>26</java.version>
        <vavr.version>0.10.6</vavr.version>
        <spring-cloud.version>2025.1.2</spring-cloud.version>
        <mapstruct.version>1.7.0.Beta2</mapstruct.version>
        <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- SPRING CLOUD (Feign BOM) -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- LAMBDAHUB COMMON -->
            <dependency>
                <groupId>ru.lambdahub</groupId>
                <artifactId>common-security</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>ru.lambdahub</groupId>
                <artifactId>common-events</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>ru.lambdahub</groupId>
                <artifactId>common-web</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>ru.lambdahub</groupId>
                <artifactId>common-kafka-starter</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>ru.lambdahub</groupId>
                <artifactId>common-redis-starter</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>ru.lambdahub</groupId>
                <artifactId>validation-vavr-starter</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </dependency>

            <dependency>
                <groupId>io.vavr</groupId>
                <artifactId>vavr</artifactId>
                <version>${vavr.version}</version>
            </dependency>


            <!-- INTER-SERVICE APIs (Feign contracts) -->
            <dependency>
                <groupId>ru.lambdahub</groupId>
                <artifactId>user-service-api</artifactId>
                <version>0.1.0-SNAPSHOT</version>
            </dependency>

            <!-- TOOLS -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
