server:
  port: 8082
spring:
  application:
    name: user-service
  config:
    import:
      - optional:classpath:kafka-stream/kafka.yml
      - optional:classpath:kafka-stream/kafka-bindings.yml
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lambdahub}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: users
      hibernate.jdbc.time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:db.changelog-master.xml
    default-schema: users
    liquibase-schema: users

app:
  media-service-url: ${MEDIA_SERVICE_URL:http://localhost:8084}
  internal-key: ${INTERNAL_KEY:internal-dev-key}
